[components]
model = "model.Wofost"
time = "pypfilt.Scalar"
sampler = "pypfilt.sampler.LatinHypercube"
summary = "pypfilt.summary.HDF5"

[time]
start = 0.0
until = 150
steps_per_unit = 1
summaries_per_unit = 1

[prior]
TDWI = { name = "norm", args.loc = 150, args.scale = 50 }
WAV = { name = "norm", args.loc = 4.5, args.scale = 1.5 }
SPAN = { name = "norm", args.loc = 31, args.scale = 3 }
SMFCF = { name = "norm", args.loc = 0.31, args.scale = 0.03 }
LAI = { name = "constant", args.value = 0 }
SM = { name = "constant", args.value = 0 }

[observations.LAI]
model = "model.WofostObs"
parameters.sdev = 0.01

[observations.SM]
model = "model.WofostObs"
parameters.sdev = 0.01

[filter]
particles = 50
prng_seed = 100
history_window = -1
resample.threshold = 0.25

[summary.tables]
forecasts.component = "pypfilt.summary.PredictiveCIs"
forecasts.credible_intervals = [50, 95]
regularisation.enabled = true

[filter.regularisation.bounds]
LAI = { min = 0, max = 10 }
SM = { min = 0, max = 2 }

[scenario.forecast.files]
#cache_file = "cache_forecast.hdf5"

[scenario.forecast_regularised.files]
#cache_file = "cache_forecast_regularised.hdf5"

[scenario.simulate]
[scenario.forecast_regularised]